apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: rahul
spec:
  containers:
  - name: test-ctr
    image: ocdr/atf-test:new
    command:
    - sh
    - -c
    - |
      echo "Hellow world"
      sleep 1000000000000000
  serviceAccountName: test-sa
