apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: test-binding
  namespace: rahul
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: test-sa
  namespace: rahul
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-sa
  namespace: rahul
