apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: create-ingress-run
  namespace: getting-started
spec:
  taskRef:
    name: create-ingress
  params:
  - name: CreateCertificate
    value: "true"
  - name: CertificateKeyPassphrase
    value: asecretphrase
  - name: CertificateSecretName
    value: ingresssecret
  - name: ExternalDomain
    value: "34.68.242.174"
  - name: Service
    value: getting-started
  - name: ServicePort
    value: "31410"
  timeout: 1000s
  serviceAccountName: tekton-triggers-createwebhook
